### ISSUE TITLE
[作業] 繳交hw7

### ISSUE THREAD

**Issue by miau715** [aszx87410/frontend-intermediate-course#106]
### slack 帳號
miau

### 哪一個作業
7. 走向國際：i18n

### 作業 Github 連結
https://github.com/miau715/frontend-intermediate-course/tree/master/answers/hw7

### 作業 Github Page 連結
https://miau715.github.io/frontend-intermediate-course/answers/hw7/index.html

**Comment by aszx87410** [comment]
都不錯，但有一個小地方可以改進
你的 selector 除了 class name 以外似乎習慣搭配 tag name 一起使用，例如說`ul.lang-list a`
如果沒有特殊需求的話，其實可以把 tag name 拿掉，用 class name 就好
可參考：https://google.github.io/styleguide/htmlcssguide.html#Type_Selectors

**Comment by miau715** [comment]
感謝建議，我也知道自己這種習慣蠻有病的（沒多寫一點就覺得好像太模糊不太牢靠XD），會試著改善 <(_ _)>
