### ISSUE TITLE
[作業]繳交 hw1

### ISSUE THREAD

**Issue by yuanyu90221** [aszx87410/frontend-intermediate-course#11]
### slack 帳號
+   yuanyu90221

### 哪一個作業
+   1.基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
+   <https://github.com/yuanyu90221/frontend-intermediate-course/tree/master/answers/hw1>

### 作業 Github Page 連結
+  <https://yuanyu90221.github.io/frontend-intermediate-course/answers/hw1/>

### 其他補充說明
+  <https://github.com/yuanyu90221/frontend-intermediate-course/blob/master/answers/hw1/README.md>

**Comment by aszx87410** [comment]
其實就算把 .mask 的 z-index 拿掉，對版面也不會有影響  
其他部分都 ok~
