### ISSUE TITLE
[繳交]hw 8

### ISSUE THREAD

**Issue by yuanyu90221** [aszx87410/frontend-intermediate-course#111]
### slack 帳號
+ yuanyu90221

### 哪一個作業
+8 當我們包在一起：Webpack

### 作業 Github 連結
+<https://github.com/yuanyu90221/frontend-intermediate-course/tree/master/answers/hw8>

### 作業 Github Page 連結
+<https://yuanyu90221.github.io/frontend-intermediate-course/answers/hw8/>

### 其他補充說明
+<https://github.com/yuanyu90221/frontend-intermediate-course/blob/master/answers/hw8/README.md>

**Comment by aszx87410** [comment]
ok，都不錯
有個小地方可以改進，`window.$ = require('jquery');`這一段，你這樣的話又用到 window 了
其實可以寫：`var $ = require('jquery');` 就好

**Comment by yuanyu90221** [comment]
感謝大大幫我解掉 uglifyjs的bug~ 終於比較理解 webpack了^ ^
