### ISSUE TITLE
[作業] 繳交hw8

### ISSUE THREAD

**Issue by miau715** [aszx87410/frontend-intermediate-course#118]
### slack 帳號
miau

### 哪一個作業
8. 當我們包在一起：Webpack

### 作業 Github 連結
https://github.com/miau715/frontend-intermediate-course/tree/master/answers/hw8

### 作業 Github Page 連結
https://miau715.github.io/frontend-intermediate-course/answers/hw8/index.html

### 其他補充說明
沒有用過 node.js 所以看了很久都一頭霧水，
雖然大致上知道這樣做的意義但各個教學中有很多步驟都難以確定是不是必要的，
最後還是主要參照 huli 大人的文章：http://ithelp.ithome.com.tw/articles/10188007
但可能因為版本差異又遇上 `import` 和 `module.exports` 不能混用的問題，
好不容易總算是寫出來了，覺得好難 +__+

**Comment by aszx87410** [comment]
哈哈，恭喜你寫出來了，又學會一個新的東西
這次作業都 ok 喔，沒什麼問題
