### ISSUE TITLE
[作業]繳交 hw1

### ISSUE THREAD

**Issue by miau715** [aszx87410/frontend-intermediate-course#12]
### slack 帳號
miau

### 哪一個作業
1.基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/miau715/frontend-intermediate-course

### 作業 Github Page 連結
https://miau715.github.io/frontend-intermediate-course/answers/hw1/index.html

### 其他補充說明
難得不用應付業主的瀏覽器需求所以沒有照說明使用 flexbox 而藉機試著用了 grid 看看 🐱

**Comment by aszx87410** [comment]
居然是最新的 grid! 厲害厲害  
`background` 的寫法可以這樣我也是現在才知道，哈哈  
學習了~
