### ISSUE TITLE
[作業] 繳交 hw9

### ISSUE THREAD

**Issue by yuanyu90221** [aszx87410/frontend-intermediate-course#120]
### slack 帳號
+ yuanyu90221

### 哪一個作業
+ 9 節省 Request 的極致：一為全，全為一

### 作業 Github 連結
+ <https://github.com/yuanyu90221/frontend-intermediate-course/tree/master/answers/hw9>

### 作業 Github Page 連結
+ <https://yuanyu90221.github.io/frontend-intermediate-course/answers/hw9/> 

### 其他補充說明
+ <https://github.com/yuanyu90221/frontend-intermediate-course/blob/master/answers/hw9/README.md>

**Comment by aszx87410** [comment]
ok 沒問題，做得很好
webpack 的部分可以用這個融合進去 gulp 的流程：https://www.npmjs.com/package/gulp-webpack

**Comment by yuanyu90221** [comment]
感謝大大
