### ISSUE TITLE
[作業] 繳交 hw9

### ISSUE THREAD

**Issue by gogogohuang** [aszx87410/frontend-intermediate-course#125]
### slack 帳號
gogogohuang

### 哪一個作業
9. 節省 Request 的極致：一為全，全為一	

### 作業 Github 連結
https://github.com/gogogohuang/frontend-intermediate-course/tree/master/answers/hw9

### 作業 Github Page 連結
https://gogogohuang.github.io/frontend-intermediate-course/answers/hw9/dist/index.html

### 其他補充說明
直接用gulp-inline發現沒有辦法直接做js minify, 查了以後發現是es6語法問題，所以在inline前先用babel編譯。

**Comment by aszx87410** [comment]
ok~沒問題
做得很好
