### ISSUE TITLE
[作業]hw10 繳交

### ISSUE THREAD

**Issue by yuanyu90221** [aszx87410/frontend-intermediate-course#127]
### slack 帳號
+ yuanyu90221

### 哪一個作業
+ 10 改掉你的壞習慣：ESLint 與 standard

### 作業 Github 連結
+ <https://github.com/yuanyu90221/frontend-intermediate-course/tree/master/answers/hw10>

### 作業 Github Page 連結
+ <https://yuanyu90221.github.io/frontend-intermediate-course/answers/hw10/>

### 其他補充說明
+ <https://github.com/yuanyu90221/frontend-intermediate-course/blob/master/answers/hw10/README.md>
+ 這次作業讓我發現自己有些不好的 coding 習慣
+ 用標準的 code style有助於檢查程式碼品質 是個很實用的章節

**Comment by aszx87410** [comment]
恭喜你完成所有作業 🎉 🎉 🎉
