### ISSUE TITLE
[作業] 繳交hw2

### ISSUE THREAD

**Issue by yuanyu90221** [aszx87410/frontend-intermediate-course#13]
### slack 帳號
+   yuanyu90221

### 哪一個作業
+   2. 讓畫面變得更動態：神奇的 CSS transition

### 作業 Github 連結
+  <https://github.com/yuanyu90221/frontend-intermediate-course/tree/master/answers/hw2>

### 作業 Github Page 連結
+   <https://yuanyu90221.github.io/frontend-intermediate-course/answers/hw2/> 

### 其他補充說明
+    <https://github.com/yuanyu90221/frontend-intermediate-course/blob/master/answers/hw2/README.md>

**Comment by aszx87410** [comment]
寫得不錯，喜歡你做的筆記，可以一目了然看到你用了哪些方法
目前只剩一些小地方需要微調，主要是一些對齊之類的細節，那就之後再說吧XD

**Comment by yuanyu90221** [comment]
對齊的地方還要跟huli大大學習^ ^
