### ISSUE TITLE
[作業] 繳交hw8

### ISSUE THREAD

**Issue by zach0429** [aszx87410/frontend-intermediate-course#136]
### slack 帳號
kenny_chen

### 哪一個作業
8. 當我們包在一起：Webpack

### 作業 Github 連結
https://github.com/kennyname/frontend-intermediate-course/tree/master/answers/hw8

### 作業 Github Page 連結
https://kennyname.github.io/frontend-intermediate-course/answers/hw8/index.html
### 其他補充說明
中文按鈕反覆按2.3次之後，資料就抓不到了...但英文卻沒有這個問題??  麻煩你了:(
另外，en: require('./lang-en.js'),
	   'zh-tw': require('./lang-zh-tw.js')
為何en不需要用引號刮起來呢??
然後  I18N[lang]['TITLE']   和  I18N[lang].TITLE  有什麼不一樣嗎??

**Comment by aszx87410** [comment]
1. 因為 zh-tw 的 - 這個符號不是合法的字，所以必須要括號刮起來變字串，你可以試試看不加括號會出什麼錯就知道了
2. 抓不到這個問題是因為你的 nowIndex 在切換語言時沒有歸零
https://github.com/kennyname/frontend-intermediate-course/blob/master/answers/hw8/js/index.js#L70
