### ISSUE TITLE
[作業]繳交hw1

### ISSUE THREAD

**Issue by EthanYa** [aszx87410/frontend-intermediate-course#15]
### slack 帳號
ethan

### 哪一個作業
1.基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/EthanYa/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://ethanya.github.io/frontend-intermediate-course/answers/hw1/index.html

**Comment by aszx87410** [comment]
大致上都 ok，頻道名字跟實況主名字那邊有時間的話可以加個 margin，然後看看能不能垂直置中。
