### ISSUE TITLE
[作業]繳交hw1

### ISSUE THREAD

**Issue by lucreciaLin** [aszx87410/frontend-intermediate-course#16]
slack 帳號

lucrelin

哪一個作業

1.基本 HTML/CSS 練習：以 Twitch 為例

作業 Github 連結

https://github.com/lucreciaLin/frontend-intermediate-course/tree/master/answers/hw1

作業 Github Page 連結

https://lucrecialin.github.io/frontend-intermediate-course/answers/hw1/index.html

其他補充說明

**Comment by aszx87410** [comment]
強烈建議 css 不要用這種方式（`.wrapper > .bg > li > div > div > figure > img {
`）來指定，不然專案變大會很想死，幫 div 加上 class 吧！

**Comment by lucreciaLin** [comment]
謝謝您, 已修改好: )
