### ISSUE TITLE
[作業] 繳交hw1

### ISSUE THREAD

**Issue by matin5** [aszx87410/frontend-intermediate-course#18]
### slack 帳號
martin

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/matin5/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://matin5.github.io/frontend-intermediate-course/answers/hw1/

### 問題
1. 為什麼圖片1中紅色箭頭指的位置會有間隔呢? 找好久，還是看不出原因...
![圖片1](https://raw.githubusercontent.com/matin5/frontend-intermediate-course/master/answers/hw1/public/images/error1.png)

2. 為什麼我在 background image 後加上 `no-repeat center`，背景會變成灰白，是我電腦的問題嗎? Safari 跟 Chrome 都一樣
```ccs
body {
  background-image: url("../images/bg-default.jpg") no-repeat center;
  background-attachment: fixed;
  margin: 0;
}
```
![圖片2](https://github.com/matin5/frontend-intermediate-course/blob/master/answers/hw1/public/images/error2.png?raw=true)

**Comment by aszx87410** [comment]
1. 這是瀏覽器預設的行為，解法可參考：[CSS学习笔记－图片img与父元素div之间的间隙解决](http://www.jianshu.com/p/057835080565)、[【CSS】圖像產生間隙，空一行，如何解決？完美解決跨瀏覽器兼容教學](https://www.pkstep.com/archives/2323)、http://www.cnblogs.com/JoannaQ/archive/2013/03/16/2962443.html

2. 這是因為 `background-image` 就只能讓你放 image，你要用 `background` 後面才能接 `no-repeat center`

**Comment by matin5** [comment]
了解，順利解決兩個問題，謝謝。

**Comment by yuanyu90221** [comment]
感謝 ，剛剛發現問題 也是我當初的問題
