### ISSUE TITLE
繳交 hw1

### ISSUE THREAD

**Issue by itsems** [aszx87410/frontend-intermediate-course#21]
### slack 帳號
itsems

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/beautyemma/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://beautyemma.github.io/frontend-intermediate-course/answers/hw1/index.html

**Comment by aszx87410** [comment]
為什麼你的 `wrap` 要設置 `max-width`?  
還有，你的 css 開頭沒寫好，導致 body 還是有 8px 的 margin。

**Comment by itsems** [comment]
不小心想成響應式的想法了，不好意思
css reset也調整上傳了，謝謝huli大大
