### ISSUE TITLE
[作業]繳交hw1

### ISSUE THREAD

**Issue by itony215** [aszx87410/frontend-intermediate-course#24]
### slack 帳號
tony

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/itony215/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://itony215.github.io/frontend-intermediate-course/answers/hw1/index.html

### 其他補充說明
無

**Comment by aszx87410** [comment]
左邊的大頭貼要是圓的喔，除此之外都 ok~
