### ISSUE TITLE
[作業]繳交hw1

### ISSUE THREAD

**Issue by decadehew** [aszx87410/frontend-intermediate-course#25]
### slack 帳號
decadehew

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/decadehew/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://decadehew.github.io/frontend-intermediate-course/answers/hw1/index.html

### 其他補充說明
學習很多更深入的方法與技巧

**Comment by aszx87410** [comment]
大致上都 ok，css 寫得不錯還有註解。  
自我練習第六題你有點誤解意思了，我想問的是這個：https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
