### ISSUE TITLE
[作業]繳交hw1

### ISSUE THREAD

**Issue by geoff8191** [aszx87410/frontend-intermediate-course#26]
### slack 帳號
srwhite

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
hw1: https://github.com/geoff8191/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
hw1: https://geoff8191.github.io/frontend-intermediate-course/answers/hw1/

### 其他補充說明
無

**Comment by aszx87410** [comment]
大致上都 ok，Good job~
