### ISSUE TITLE
HW1作業繳交

### ISSUE THREAD

**Issue by sklack** [aszx87410/frontend-intermediate-course#27]
### slack 帳號
jenan
### 哪一個作業
基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
hw1: https://github.com/sklack/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://sklack.github.io/frontend-intermediate-course/answers/hw1/index.html

**Comment by aszx87410** [comment]
左邊的大頭貼要是圓的喔～
