### ISSUE TITLE
[作業] 繳交hw1

### ISSUE THREAD

**Issue by ponponwu** [aszx87410/frontend-intermediate-course#29]
### slack 帳號
vincentwu

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/ponponwu/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://ponponwu.github.io/frontend-intermediate-course/answers/hw1/index.html

### 其他補充說明
痛恨CSS..

**Comment by aszx87410** [comment]
儘管痛恨 CSS，但你做得滿不錯的啊XD
