### ISSUE TITLE
[作業] 繳交 hw 2

### ISSUE THREAD

**Issue by pychiang** [aszx87410/frontend-intermediate-course#32]
### slack 帳號
pychiang

### 哪一個作業
2. 讓畫面變得更動態：神奇的 CSS transition

### 作業 Github 連結
[https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw2](https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw2)

### 作業 Github Page 連結
[https://pychiang.github.io/frontend-intermediate-course/answers/hw2/index.html](https://pychiang.github.io/frontend-intermediate-course/answers/hw2/index.html)

### 其他補充說明
CSS prefixes 是利用 Autoprefixer

**Comment by aszx87410** [comment]
1. 檔案名稱其實可以一樣叫做 index.html 就好，比較有一致性
2. 滑鼠移到圖片上面會變色塊，是你在測試什麼嗎XD
3. 可以試著幫 box-shadow 加上 transition 看看，效果會更好

**Comment by pychiang** [comment]
1. 已修改檔名
2. 只是嘗試回答自我練習中的第一題而做的 XD
3. 已加入 transition
