### ISSUE TITLE
[作業] 繳交hw2

### ISSUE THREAD

**Issue by waiwai0308** [aszx87410/frontend-intermediate-course#34]
### slack 帳號
weizhi

### 哪一個作業
讓畫面變得更動態：神奇的 CSS transition

### 作業 Github 連結
https://github.com/waiwai0308/frontend-intermediate-course/tree/master/answers/hw2

### 作業 Github Page 連結
https://waiwai0308.github.io/frontend-intermediate-course/answers/hw2/index.html

### 其他補充說明
無

**Comment by aszx87410** [comment]
ok~
