### ISSUE TITLE
[作業] 繳交hw2

### ISSUE THREAD

**Issue by EthanYa** [aszx87410/frontend-intermediate-course#35]
### slack 帳號
ethan

### 哪一個作業
2. 讓畫面變得更動態：神奇的 CSS transition 

### 作業 Github 連結
https://github.com/EthanYa/frontend-intermediate-course/tree/master/answers/hw2

### 作業 Github Page 連結
https://ethanya.github.io/frontend-intermediate-course/answers/hw2/index.html

### 其他補充說明
無

**Comment by aszx87410** [comment]
brightness 那邊沒有 transition 到喔，你會發現滑鼠一移上去就直接變亮，可以修一下
