### ISSUE TITLE
[作業]繳交Hw2

### ISSUE THREAD

**Issue by gogogohuang** [aszx87410/frontend-intermediate-course#38]
### slack 帳號
gogogohuang

### 哪一個作業
2. 讓畫面變得更動態：神奇的 CSS transition

### 作業 Github 連結
https://github.com/gogogohuang/frontend-intermediate-course/tree/master/answers/hw2

### 作業 Github Page 連結
https://gogogohuang.github.io/frontend-intermediate-course/answers/hw2/index.html

### 其他補充說明
1. 重新用flex排版。
2. 想問如何取消掉大頭貼的hover效果？想達到的效果是讓filter效果不在大頭貼上面運行。目前想到的辦法是分開實現filter。可以取消child的hover效果嗎？目前找到的pointer-event 好像在child無法work.@@

**Comment by advancedor96** [comment]
我猜想是讓左下角的大頭貼失效(讓滑鼠移到大頭貼時，不讓 transition 作用。)

**Comment by gogogohuang** [comment]
是的，不過我用了pointer-event沒辦法work@@

**Comment by aszx87410** [comment]
你的意思是滑鼠移上去的時候，只有大頭貼不要跟著發亮嗎？
如果是的話，我目前只跟你一樣想到分開實現 filter，感覺不太好做

**Comment by gogogohuang** [comment]
是的。我今天打算用分開實現了@@
