### ISSUE TITLE
[作業] 繳交Hw2

### ISSUE THREAD

**Issue by itsems** [aszx87410/frontend-intermediate-course#39]
slack 帳號

itsems

哪一個作業

基本 HTML/CSS 練習：以 Twitch 為例
作業 Github 連結

https://github.com/beautyemma/frontend-intermediate-course/tree/master/answers/hw2

作業 Github Page 連結

https://beautyemma.github.io/frontend-intermediate-course/answers/hw2/index.html

**Comment by advancedor96** [comment]
作業2是「2. 讓畫面變得更動態：神奇的 CSS transition」啦XD

**Comment by aszx87410** [comment]
除了忘記改作業名稱以外，其他都 ok XD
