### ISSUE TITLE
[作業] 繳交 hw2

### ISSUE THREAD

**Issue by clingoram** [aszx87410/frontend-intermediate-course#42]
### slack 帳號

vis_oram
### 哪一個作業

2. 讓畫面變得更動態：神奇的 CSS transition
### 作業 Github 連結

https://github.com/clingoram/frontend-intermediate-course/tree/master/answers/hw2
### 作業 Github Page 連結

https://clingoram.github.io/frontend-intermediate-course/answers/hw2/index.html

**Comment by advancedor96** [comment]
一行最多是3個，當瀏覽器zoom out時，一行會出現5,6個XD
我是用max-width來解決這個問題。

**Comment by aszx87410** [comment]
的確，照目前的排版來說會有這個問題。
但其實我後來想了一下，其實變多變少都滿合理的，一開始我只是想要簡化問題而已，其實變多變少也沒差
畢竟 RWD 就應該這樣做XD
