### ISSUE TITLE
[作業] 繳交hw2

### ISSUE THREAD

**Issue by matin5** [aszx87410/frontend-intermediate-course#43]
slack 帳號

martin

哪一個作業

讓畫面變得更動態：神奇的 CSS transition

作業 Github 連結

https://github.com/matin5/frontend-intermediate-course/tree/master/answers/hw2

作業 Github Page 連結

https://matin5.github.io/frontend-intermediate-course/answers/hw2/

**Comment by advancedor96** [comment]
沒有shadow 哭哭

**Comment by matin5** [comment]
真的ㄟ，沒注意到，謝謝丁丁大提醒~~~

**Comment by advancedor96** [comment]
哈哈 ^^

**Comment by aszx87410** [comment]
transition 的效果怪怪的喔，只有移上去的時候有，移出來的時候就沒了。
主要是因為你 transition 加錯地方，不應該加在 :hover 上

**Comment by matin5** [comment]
改好了，謝謝提醒哦，感恩。
