### ISSUE TITLE
[作業] 繳交 hw 1

### ISSUE THREAD

**Issue by pychiang** [aszx87410/frontend-intermediate-course#5]
### slack 帳號
pychiang

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
[https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw1](https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw1)

### 作業 Github Page 連結
[https://pychiang.github.io/frontend-intermediate-course/answers/hw1/index.html](https://pychiang.github.io/frontend-intermediate-course/answers/hw1/index.html)

### 其他補充說明
無

**Comment by aszx87410** [comment]
連結沒有用對喔，請參考：http://markdown.tw/#link

**Comment by pychiang** [comment]
已修改連結。原本是用 GitHub 編輯器上面的 Add a link，可能我沒有用正確

**Comment by yuanyu90221** [comment]
我是看huli大大的那篇markdown 才開始研究markdown的大推 http://markdown.tw/#link

**Comment by aszx87410** [comment]
row1 row2 row2 那邊，其實都有一些共同的 CSS，就像你寫到的那樣：

```
.row1, .row2, .row3 {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-self: center
  overflow: hidden;
}
```

建議改成：

```
.row {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  align-self: center
  overflow: hidden;
}
```

然後 HTML 那邊就變成這樣：
```
<div class="row row1">
  ....
</div>
```

這樣子的擴充性會比較高一點，否則你每新增一個 row，就要去改一遍 CSS

還有一個可以改進的地方是把實況主名稱跟頻道名稱那邊垂直置中對齊

**Comment by pychiang** [comment]
好的，謝謝！
