### ISSUE TITLE
[作業] 繳交hw2

### ISSUE THREAD

**Issue by sklack** [aszx87410/frontend-intermediate-course#50]
### slack 帳號
jenan

### 哪一個作業
2. 讓畫面變得更動態：神奇的 CSS transition

### 作業 Github 連結
hw1: https://github.com/sklack/frontend-intermediate-course/tree/master/answers/hw2

### 作業 Github Page 連結
https://sklack.github.io/frontend-intermediate-course/answers/hw2/index.html

**Comment by aszx87410** [comment]
@sklack  你是不是改東西改一改忘記改回來，hover 沒效果喔XD
