### ISSUE TITLE
[作業] 繳交hw2

### ISSUE THREAD

**Issue by decadehew** [aszx87410/frontend-intermediate-course#51]
### slack 帳號
decadehew

### 哪一個作業
2. 讓畫面變得更動態：神奇的 CSS transition 

### 作業 Github 連結
https://github.com/decadehew/frontend-intermediate-course/tree/master/answers/hw2

### 作業 Github Page 連結
https://decadehew.github.io/frontend-intermediate-course/answers/hw2/index.html 

### 其他補充說明
這次作業是用huli老師作業1去模仿和做，理解後，覺得學到很多技巧，不錯實踐。
然後在用作業2要求進行把畫面更有動態，感覺有點象動畫圖。
希望可以學到老師寫網頁思考方式和技巧。

**Comment by aszx87410** [comment]
transition 加錯地方囉～應該加在 .class 上面而不是 .class:hover
