### ISSUE TITLE
[作業] 繳交 hw3

### ISSUE THREAD

**Issue by pychiang** [aszx87410/frontend-intermediate-course#53]
### slack 帳號
pychiang

### 哪一個作業
3. 寫 CSS 必備神器：CSS 預處理器

### 作業 Github 連結
[https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw3](https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw3)

### 作業 Github Page 連結
[https://pychiang.github.io/frontend-intermediate-course/answers/hw3/index.html](https://pychiang.github.io/frontend-intermediate-course/answers/hw3/index.html)

### 其他補充說明
1. 在 Sass 檔案中並未加入 prefix mixin，而是編譯成 CSS 檔後使用 Sublime plugin [Autoprefixer](https://packagecontrol.io/packages/Autoprefixer)。
2. 在 Sublime 上 Sass 檔案編譯成 CSS 後會自動產生 sourcemap，我沒有刪除。

**Comment by aszx87410** [comment]
Good! 很不錯
