### ISSUE TITLE
繳交作業4

### ISSUE THREAD

**Issue by zach0429** [aszx87410/frontend-intermediate-course#64]
### slack 帳號
kennyname

### 哪一個作業
4. 從假資料到真資料：Ajax 與 API 串接

### 作業 Github 連結
https://github.com/kennyname/frontend-intermediate-course/blob/master/answers/hw4/index.html

### 作業 Github Page 連結
https://kennyname.github.io/frontend-intermediate-course/answers/hw4/index.html

### 其他補充說明
不好意思，前幾次作業沒有跟到，這次全部補在一起
有些實況沒圖片，所以呈現畫面這樣是ok的嗎?
然後flex 由於呈現畫面是20組，最後一排會破版，但運用老師第一次影片所說的解決方式
最後加上"div class='col'"還是沒有改善
希望老師給個idea 謝謝。

**Comment by ckchuang-dev** [comment]
沒有圖片應該是因為你抓到實況主橫幅的圖片(有些沒放)，應該是要抓實況縮圖。你flex問題我之前也有遇過，不過我是把flex屬性加在container上，我把space-around拿掉就可以依序排列，詳解交給Huli大大，小弟路過XD

**Comment by zach0429** [comment]
感謝你，圖片問題已解決，但排版還是無法...

**Comment by ckchuang-dev** [comment]
我試了一下，把你的.container改了一下就可以了，然後不確定你.box的display: inline-block是否需拿掉
```
.container {
    width: 1000px;
    margin: 0 auto;
    padding-top: 30px;
    text-align: center;
    display: flex;
    flex-wrap: wrap;
}
```

**Comment by zach0429** [comment]
真的大感謝!!困擾很久了
完全沒想到wrap這個屬性!
謝謝你~

**Comment by aszx87410** [comment]
@kennyname 你有更新上去了嗎？
因為我這邊點開來看，最後一行的版面還是錯的

另外也感謝 @DezChuang 同學的熱心 debug XD

**Comment by zach0429** [comment]
不好意思，已改過!

**Comment by aszx87410** [comment]
@kennyname 
版面正常了，但還是有問題喔
1. hover 上去有 transition 但移開的時候沒有
2. 往下捲的時候背景沒固定

**Comment by zach0429** [comment]
也更改上去囉~
