### ISSUE TITLE
[作業] 繳交hw3

### ISSUE THREAD

**Issue by decadehew** [aszx87410/frontend-intermediate-course#66]
### slack 帳號
decadehew

### 哪一個作業
寫 CSS 必備神器：CSS 預處理器

### 作業 Github 連結
https://github.com/decadehew/frontend-intermediate-course/tree/gh-pages/answers/hw3

### 作業 Github Page 連結
https://decadehew.github.io/frontend-intermediate-course/answers/hw3/index.html

### 其他補充說明
遲交作業，不好意思，因為有點事情要處理。
這次作業我用老師推薦stylus預處理器，覺得還不錯，因為第一次用，一直在深入研究stylus 文檔學習。
請問如果到了業界，大多數公司會用哪個比較多，如果我繼續學習stylus的話，有需要學習sass？

**Comment by aszx87410** [comment]
標題應該是 hw3 才對喔

業界的話應該是 sass 會用得比較多一點
但其實兩個的原理跟語法都滿類似的，到時候就算要轉到 sass 也很快
