### ISSUE TITLE
[作業]繳交hw4

### ISSUE THREAD

**Issue by waiwai0308** [aszx87410/frontend-intermediate-course#67]
### slack 帳號
weizhi

### 哪一個作業
4. 從假資料到真資料：Ajax 與 API 串接

### 作業 Github 連結
https://github.com/waiwai0308/frontend-intermediate-course/tree/master/answers/hw4

### 作業 Github Page 連結
https://waiwai0308.github.io/frontend-intermediate-course/answers/hw4/index.html

### 其他補充說明
剛好在學JavaScript所以沒用jQuery，希望後面作業不會搞死自己QQ

**Comment by aszx87410** [comment]
做得好！
等你撐到第六個作業就海闊天空了，因為第六個作業就是禁止用 jQuery，剛好你現在就達成了XD
