### ISSUE TITLE
[作業]繳交 hw1

### ISSUE THREAD

**Issue by waiwai0308** [aszx87410/frontend-intermediate-course#7]
### slack 帳號
weizhi

### 哪一個作業
1. 基本 HTML/CSS 練習：以 Twitch 為例

### 作業 Github 連結
https://github.com/waiwai0308/frontend-intermediate-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://waiwai0308.github.io/frontend-intermediate-course/answers/hw1/index.html

### 其他補充說明
無

**Comment by aszx87410** [comment]
看起來大致上都 OK，沒什麼問題。  
有時間的話可以練習看看除了 `float` 以外的排版方式，例如說 `inline-block` 或是 `flexbox`。
