### ISSUE TITLE
[作業] 繳交 hw4

### ISSUE THREAD

**Issue by pychiang** [aszx87410/frontend-intermediate-course#70]
### slack 帳號
pychiang

### 哪一個作業
4. 從假資料到真資料：Ajax 與 API 串接

### 作業 Github 連結
[https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw4](https://github.com/pychiang/frontend-intermediate-course/tree/master/answers/hw4)

### 作業 Github Page 連結
[https://pychiang.github.io/frontend-intermediate-course/answers/hw4/index.html](https://pychiang.github.io/frontend-intermediate-course/answers/hw4/index.html)

### 其他補充說明
1. 預覽畫面可以點擊進入該實況主的 twitch 直播（單純練習用的 XD）
2. 感覺我的 Ajax 是暴力解法 XD

**Comment by aszx87410** [comment]
都不錯～
點進去要到直播那個加的很好，原本應該就要這樣加的但我忘記講了XD
append 那一段可以排版一下，例如說：

```
$('.container').append(
  '<div class="viewbox">' + 
    '<div class="preview">' + '
      <a href="' + url + '" target="_blank">' + .....
```

**Comment by pychiang** [comment]
已修改。昨天我自己也看得超眼花，當時頭昏沒想到可以用連接字串的方式排版 XD
