### ISSUE TITLE
[作業]繳交hw4

### ISSUE THREAD

**Issue by Yuki0916** [aszx87410/frontend-intermediate-course#71]
slack 帳號

yuki

哪一個作業

從假資料到真資料：Ajax 與 API 串接

作業 Github 連結

https://github.com/Yuki0916/frontend-intermediate-course/blob/master/answers/hw4

作業 Github Page 連結

https://yuki0916.github.io/frontend-intermediate-course/answers/hw4/index.html

**Comment by aszx87410** [comment]
最後一行的排版跑掉喔

**Comment by Yuki0916** [comment]
排版問題已修正
