### ISSUE TITLE
[作業]繳交hw1

### ISSUE THREAD

**Issue by abvdsk** [aszx87410/frontend-intermediate-course#8]
### slack 帳號
abvdsk

### 哪一個作業
hw1

### 作業 Github 連結
https://github.com/abvdsk/frontend-course/tree/master/answers/hw1

### 作業 Github Page 連結
https://abvdsk.github.io/frontend-course/answers/hw1/index.html

**Comment by aszx87410** [comment]
做得不錯～可以繼續寫之後的作業囉
