### ISSUE TITLE
[作業] 繳交 hw5

### ISSUE THREAD

**Issue by yuanyu90221** [aszx87410/frontend-intermediate-course#81]
### slack 帳號
+yuanyu90221

### 哪一個作業
+讓網頁變得更完整：加上 placeholder 與 infinite scroll

### 作業 Github 連結
<https://github.com/yuanyu90221/frontend-intermediate-course/blob/master/answers/hw5/>

### 作業 Github Page 連結
<https://yuanyu90221.github.io/frontend-intermediate-course/answers/hw5/>

### 其他補充說明
<https://github.com/yuanyu90221/frontend-intermediate-course/blob/master/answers/hw5/README.md>

**Comment by aszx87410** [comment]
大致上都不錯
不過我沒有很懂`appendDataToDOM `這個 function 裡的 `isFirst` 的作用，可以解釋一下嗎？

**Comment by yuanyu90221** [comment]
@aszx87410 大大 那個主要用來控制 監控是不是第一次loadData還是refresh過之後loadData 原本是用來壁面不斷refesh 會一直appendData 而只有在scroll才去處理 loadData
