### ISSUE TITLE
[作業]繳交hw5

### ISSUE THREAD

**Issue by waiwai0308** [aszx87410/frontend-intermediate-course#86]
### slack 帳號
weizhi

### 哪一個作業
5. 讓網頁變得更完整：加上 placeholder 與 infinite scroll	

### 作業 Github 連結
https://github.com/waiwai0308/frontend-intermediate-course/tree/master/answers/hw5

### 作業 Github Page 連結
https://waiwai0308.github.io/frontend-intermediate-course/answers/hw5/index.html

### 其他補充說明
這次真的有點困難QQ，捲動偵測那邊的code就直接引用別人的code，等消化完再試試改寫。

**Comment by aszx87410** [comment]
function 的命名建議統一規則喔，例如說開頭統一小寫之類的，其他都還 ok
