### ISSUE TITLE
[作業] 繳交hw5,hw6

### ISSUE THREAD

**Issue by ponponwu** [aszx87410/frontend-intermediate-course#90]
### slack 帳號
vincentwu

### 哪一個作業
hw5, hw6
### 作業 Github 連結
https://github.com/ponponwu/frontend-intermediate-course/tree/master/answers/hw5

### 作業 Github Page 連結

https://ponponwu.github.io/frontend-intermediate-course/answers/hw5/index.html

### 其他補充說明

有參考網路上的資源
昨天聽完huli大講的才發現根本不需要這麼多工
不過還是先貼一下哈
自己再另外修改

**Comment by aszx87410** [comment]
寫得不錯喔，有很多地方都有考慮到各個瀏覽器或是各種 case
