### ISSUE TITLE
[作業]繳交hw5&6

### ISSUE THREAD

**Issue by Yuki0916** [aszx87410/frontend-intermediate-course#93]
slack 帳號

yuki

哪一個作業

讓網頁變得更完整：加上 placeholder 與 infinite scroll
返璞歸真：vanilla js

作業 Github 連結

https://github.com/Yuki0916/frontend-intermediate-course/blob/master/answers/hw5

作業 Github Page 連結

https://yuki0916.github.io/frontend-intermediate-course/answers/hw5/index.html

其他補充說明

想不到怎麼利用pseudo element處理最後一行不會跑版的問題，就先在flex-container底下使用justify-content: start跟channel 使用margin來實作

**Comment by aszx87410** [comment]
咦，為什麼要用 pseudo element 來處理？

另外有幾個小建議：
1. `buildChannel `那邊程式碼有點冗長，可以考慮改成用字串加上 innerHTML 的方式設置即可（可參考其他同學作業）
2. 104 行跟 121 行的兩段程式碼其實重複性很高，可以考慮先宣告好然後重複使用，畢竟只有 offset 這個值會不一樣而已

**Comment by Yuki0916** [comment]
hi @aszx87410  你提出的建議我都把程式碼重新建構好了，有空麻煩幫我檢查一下　3Q!

**Comment by aszx87410** [comment]
檢查過了，都 ok 喔～
