### ISSUE TITLE
[作業] 繳交 hw5

### ISSUE THREAD

**Issue by zach0429** [aszx87410/frontend-intermediate-course#96]
### slack 帳號
kenny_chen

### 哪一個作業
讓網頁變得更完整：加上 placeholder 與 infinite scroll

### 作業 Github 連結
https://github.com/kennyname/frontend-intermediate-course/tree/master/answers/hw5

### 作業 Github Page 連結
https://kennyname.github.io/frontend-intermediate-course/answers/hw5/index.html

**Comment by aszx87410** [comment]
基本上沒什麼問題，但是有一段排版亂了喔
https://github.com/kennyname/frontend-intermediate-course/blob/master/answers/hw5/js/index.js#L43-L62
