### ISSUE TITLE
[作業] 繳交 hw6

### ISSUE THREAD

**Issue by zach0429** [aszx87410/frontend-intermediate-course#97]
slack 帳號
kenny_chen

哪一個作業
返璞歸真：vanilla js

### 作業 Github 連結
https://github.com/kennyname/frontend-intermediate-course/tree/master/answers/hw6

### 作業 Github Page 連結
https://kennyname.github.io/frontend-intermediate-course/answers/hw6/index.html

### 其他補充說明
請問老師:
DOMContentLoaded和load的差別是:
DOMContentLoaded是當html的標籤只要載入完成就會觸發
load則是還需要等圖片及css載入後才會觸發
這樣理解有錯誤嗎??

**Comment by aszx87410** [comment]
基本上都沒什麼問題

至於你問的那個問題，是這樣沒錯
可參考：https://developer.mozilla.org/zh-TW/docs/Web/Events/DOMContentLoaded
更詳細可以參考這篇：http://www.alloyteam.com/2014/03/effect-js-css-and-img-event-of-domcontentloaded/
